### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Fandekasp** [brycedrennan/eulerian-magnification#11]
With a 35" video (58MB), I get a frame_count of 1179, a height of 1080 and width of 1920.

Since you're creating a 4d matrix of uint8 zeros, this means:

```
In[1] > print "{} TB required!".format(1179 * 1080 * 1920 * 3 * 256.0 / 1024**4)
1.70765519142 TB required!
```

I would need to degrade my video to 320*180 in order to have a feasible (48.5GB) size, and I assume the result will be disastrous. 

Do you have an idea for a better way to handle this magnification, which doesn't require 30872 times more memory than the input video size ?

Thanks for your suggestions

**Comment by brycedrennan** [comment]
It's been a while since I worked on this project so I probably won't be much help. One thing that might help is to tweak the pyramid to be of a lower resolution despite the videos resolution. Other than that I don't know sorry.

**Comment by Fandekasp** [comment]
Ok. thanks for the answer.
