### ISSUE TITLE
Bad output

### ISSUE THREAD

**Issue by AndreasMadsen** [brycedrennan/eulerian-magnification#12]
I tried running your `example.py` file with the `face.mp4` file from http://people.csail.mit.edu/mrub/vidmag/. The `show_frequencies` appears to work, but `eulerian_magnification` produced a bad video file. VLC won't play it, and it is only 414 bytes.

Here is the log:

```
Loading media/face.mp4
/Users/Andreas/Sites/lies/eulerian_magnify.py:87: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if frame == None or x >= frame_count:
29
/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py:462: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
Loading /Users/Andreas/Sites/lies/media/face.mp4
Applying bandpass between 0.833333333333 and 1.0 Hz
Amplifying signal by factor of 50
/Users/Andreas/Sites/lies/eulerian_magnify.py:147: ComplexWarning: Casting complex values to real discards the imaginary part
  img[:] = g_video[x]
```

**Comment by felipecocco** [comment]
+ 1

**Comment by brycedrennan** [comment]
I've updated the library to work with python 3 and opencv 3. You may find it easier to use now.

**Comment by brycedrennan** [comment]
@felipecocco @AndreasMadsen were you able to get this working eventually?

**Comment by AndreasMadsen** [comment]
Unfortunately no.

**Comment by biaojiang** [comment]
I also tested face.mp4, it worked well on Python 3.5 and OpenCV 3.1.0, one problem is the output .avi file can't be played on a laptop, however, another desktop computer can play it. So, are there any errors during video file writing?

Another question is which version should I use? by pip install or just download files here? with these two methods, the number of files are different.

**Comment by biaojiang** [comment]
In the function of "temporal_bandpass_filter", the  two lines of "fft[bound_high:-bound_high] = 0
 fft[-bound_low:] = 0" should be replaced with "fft[bound_high + 2 :] = 0"

**Comment by brycedrennan** [comment]
Perhaps try working in the new docker environment?

**Comment by biaojiang** [comment]
Now, I have my own codes, not using opencv to record videos.
