### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by pstn** [brycedrennan/eulerian-magnification#13]
This repository has no license. Am I allowed to relicense it to some FOSS license GPL/BSD (I don't really care) to fork it and base some other functionality on it?

**Comment by brycedrennan** [comment]
I'm not super familiar with my options. I see MIT a lot so I'll probably go with that. Any concerns?

**Comment by pstn** [comment]
I think GPL and MIT/BSD are the most common ones. The main difference is that the GPL is viral in a sense that all derived works also need to be licensed under GPL, while MIT/BSD allows everybody to keep derived works proprietary.

**Comment by brycedrennan** [comment]
Fixed.
