### ISSUE TITLE
Little spelling

### ISSUE THREAD

**Issue by SecretSauSE** [brycedrennan/eulerian-magnification#14]
Still haven't had this working but I've noticed that some of the code is written eulErian-magnification while other parts say eulArian-Magnification. I'm new to python and coding so this might be a silly question: Do I need to CD to /media/face.mp4 to run the script? I keep getting a gaussian image error

eulerian_magnification() got an unexpected keyword argument 'image_processing'

**Comment by Dkmister** [comment]
The correct calling is eularian_magnification, the same name as the library.

**Comment by aayusharora** [comment]
@Dkmister It is still gave the same error `eularian_magnification() got an unexpected keyword argument 'image_processing'
`

**Comment by brycedrennan** [comment]
I fixed the spelling to be consistent and correct. It's been so long since I used this code I can't provide support unfortunately. It may be totally wrong.
