### ISSUE TITLE
Spelling Error : Readme.md

### ISSUE THREAD

**Issue by aayusharora** [brycedrennan/eulerian-magnification#15]
In Readme.md 
The spelling of `eularian` is wrong.
Correct version :

 import eularian_magnification as em
em.eularian_magnification('videos/baby.mp4', image_processing='gaussian', pyramid_levels=3, freq_min=50.0 / 60.0, freq_max=1.0, amplification=50) `
`

**Comment by brycedrennan** [comment]
Please submit a pull request and I will merge.

**Comment by brycedrennan** [comment]
Nevermind - fixed.
