### ISSUE TITLE
Real Time Implementation of Eulerian-Magnification

### ISSUE THREAD

**Issue by aayusharora** [brycedrennan/eulerian-magnification#16]
Hi, @brycedrennan 
As a part of an academic project, we want to use this algorithm to detect respiration of babies and identifying the pattern of respiration in real-time with a help of simple mobile camera.This can be useful to various hospitals to replace the sensors used on infant body.
For now, the problem we are facing is the processing time this algorithm requires when a real-time video stream is passed into this. 
I hope you can help us in figuring out the best approach that can give us real-time results.
Thanks :)

**Comment by brycedrennan** [comment]
Yeah that is tricky. I don't really know how I'd do that offhand. I suspect this code doesn't even do it right for the files.

**Comment by mark-orion** [comment]
You may want to have a look at my project PyFSPro https://github.com/mark-orion/PyFSPro
The Python Frame Sequence Processor was initially designed for Schlieren Videography, but can detect and amplify any form of subtle change in the video stream. The vectorscope function might be of interest for you as it offers a numeric output of the detected changes. It would not be too difficult to put an FFT filter in the vectorscope output to isolate typical breathing frequencies. Feel free to get in contact with me if you need further help.
