### ISSUE TITLE
ReadMe show_frequencies example

### ISSUE THREAD

**Issue by paravorheim** [brycedrennan/eulerian-magnification#19]
I was trying to run show_frequencies(vid_data) as described but had two issues:

1. The function requires a second fps argument. I imagine that the readme could be updated to say that.
2. after adding the fps argument, kept on getting an type error with vid_data (my video filename) being used as a string. I believe the best method is to load the video with cv2, then use that in show_frequencies.  It wasn't made clear to me that this was necessary from the readme, but the actual code seems to suggest that the argument 'vid_data' needs to already be something loaded in, not just a filename.

**Comment by brycedrennan** [comment]
To be honest I really doubt that the code works. I haven't worked on this project for a long time but I will gladly review pull requests to improve the documentation.

**Comment by brycedrennan** [comment]
Great point. I'll update the docs.

**Comment by brycedrennan** [comment]
Updated the docs.
