### ISSUE TITLE
Issue about invoking parameter

### ISSUE THREAD

**Issue by hek14** [brycedrennan/eulerian-magnification#20]
When I try to call the top function just like the usage following:
 em.eulerian_magnification('media/face.mp4', image_processing='gaussian', pyramid_levels=3, freq_min=50.0 / 60.0, freq_max=1.0, amplification=50);
I find that the first parameter doesn't make sense because it's a string, not a video object. And in the eulerian_magnification function, there is no preprocess about the first parameter which should obtain an object like a video. So I get a error when the program comes to  'for frame_number, frame in enumerate(video)' in the pyramid.py(line 37) because the first parameter isn't  an iterable object. What should I do solve this question?

**Comment by brycedrennan** [comment]
Great point. I'll update the docs

**Comment by brycedrennan** [comment]
Updated the docs.
